/* Frases para practicar inglés. Cada frase: [inglés, español, tip de pronunciación (opcional)].
   El tip escribe en mayúscula la sílaba fuerte. */
var PHRASES=[
 {k:'✈️ Aeropuerto y migración',l:[
  ['I’m here on vacation for three weeks.','Estoy de vacaciones por tres semanas.','vacation = vei-KÉI-shon · three: lengua entre los dientes'],
  ['I’m visiting some friends in Arlington, Virginia.','Vengo a visitar a unos amigos en Arlington, Virginia.','friends = FRENDS (la “i” no suena)'],
  ['I’ll be staying with them for the whole trip.','Me voy a quedar con ellos todo el viaje.','whole = JÓUL (la “w” no suena)'],
  ['My return flight is on November twenty-third.','Mi vuelo de regreso es el 23 de noviembre.','twenty-third = TUÉN-ti TZERD'],
  ['Here is my passport and my return ticket.','Aquí está mi pasaporte y mi tiquete de regreso.'],
  ['I don’t have anything to declare.','No tengo nada que declarar.','declare = di-KLÉR'],
  ['Where is the baggage claim?','¿Dónde se reclama el equipaje?','baggage = BÁ-guich'],
  ['My bag didn’t arrive.','Mi maleta no llegó.'],
  ['Where is the exit to the Silver Line?','¿Dónde está la salida a la línea plateada?'],
  ['Is this the line for visitors?','¿Esta es la fila de visitantes?'],
  ['Where can I get an Uber?','¿Dónde puedo tomar un Uber?','Uber = IÚ-ber'],
  ['Which gate does the flight to Bogotá leave from?','¿De qué puerta sale el vuelo a Bogotá?']]},
 {k:'🚇 Metro y tren',l:[
  ['Which train goes to Union Station?','¿Qué tren va a Union Station?','Union = IÚ-nion'],
  ['Is this the right platform for New York?','¿Es el andén correcto para Nueva York?','platform = PLÁT-form'],
  ['How many stops to Times Square?','¿Cuántas paradas hasta Times Square?'],
  ['Excuse me, is this seat taken?','Disculpe, ¿este puesto está ocupado?','seat = SIIT (i larga)'],
  ['Does this train stop at Wilmington?','¿Este tren para en Wilmington?'],
  ['How do I add money to my SmarTrip card?','¿Cómo le recargo plata a mi tarjeta SmarTrip?'],
  ['Is this the express or the local train?','¿Este es el tren expreso o el que para en todas?'],
  ['What time is the last train back?','¿A qué hora sale el último tren de regreso?'],
  ['Which exit is closest to the museum?','¿Qué salida queda más cerca del museo?','closest = KLÓU-sest'],
  ['Our train was cancelled. What should we do?','Cancelaron nuestro tren. ¿Qué hacemos?'],
  ['Two tickets to Baltimore, round trip, please.','Dos tiquetes a Baltimore, ida y vuelta, por favor.','round trip = RÁUND TRIP']]},
 {k:'🚕 Uber y direcciones',l:[
  ['Hi, I’m Santiago. Are you here for me?','Hola, soy Santiago. ¿Viene por mí?'],
  ['Could you drop us off at the main entrance?','¿Nos puede dejar en la entrada principal?','entrance = ÉN-trans'],
  ['How far is it from here?','¿Qué tan lejos queda de aquí?'],
  ['Is it walking distance?','¿Se puede ir caminando?','walking = UÓ-king (la “l” no suena)'],
  ['Go straight and turn left at the light.','Siga derecho y voltee a la izquierda en el semáforo.','straight = STRÉIT'],
  ['It’s on the corner of Fifth Avenue.','Queda en la esquina de la Quinta Avenida.','fifth = FIFZ'],
  ['Could you show me on the map?','¿Me lo puede mostrar en el mapa?'],
  ['We’re going to the same place.','Vamos para el mismo lugar.']]},
 {k:'🍔 Restaurante y comida',l:[
  ['Can I get a coffee with milk, please?','¿Me da un café con leche, por favor?','coffee = KÓ-fi'],
  ['For here or to go? — To go, please.','¿Para aquí o para llevar? — Para llevar.'],
  ['What do you recommend?','¿Qué me recomienda?','recommend = re-ko-MÉND'],
  ['A table for two, please.','Una mesa para dos, por favor.','table = TÉI-bol'],
  ['Could we see the menu?','¿Podemos ver la carta?','menu = MÉ-niu'],
  ['I’ll have the chicken sandwich.','Yo quiero el sándwich de pollo.','chicken = CHÍ-ken'],
  ['Can I get it without onions?','¿Me lo da sin cebolla?','onions = Á-nions'],
  ['Is this spicy?','¿Esto pica?'],
  ['Can we split the check?','¿Podemos dividir la cuenta?','check = CHEK'],
  ['Is the tip included?','¿La propina está incluida?'],
  ['Could I get a glass of water?','¿Me regala un vaso de agua?','water = UÁ-rer (la “t” suena casi como “r”)'],
  ['Everything was delicious, thank you!','¡Todo estuvo delicioso, gracias!','delicious = di-LÍ-shos']]},
 {k:'💳 Pagar',l:[
  ['Can I pay by card?','¿Puedo pagar con tarjeta?'],
  ['Do you take cash?','¿Reciben efectivo?'],
  ['How much is it with tax?','¿Cuánto es con impuestos?','tax = TAKS'],
  ['Could you charge it in dollars?','¿Me lo puede cobrar en dólares?'],
  ['Sorry, I think there’s a mistake on the bill.','Perdón, creo que hay un error en la cuenta.','mistake = mis-TÉIK'],
  ['Keep the change.','Quédese con el cambio.'],
  ['Where is the nearest ATM?','¿Dónde queda el cajero más cercano?','ATM = ei-ti-ÉM']]},
 {k:'🛍️ Compras',l:[
  ['Do you have this in a medium?','¿Tiene esto en talla M?','medium = MÍ-diom'],
  ['Can I try this on?','¿Me lo puedo probar?'],
  ['Where are the fitting rooms?','¿Dónde están los probadores?'],
  ['Is there any discount today?','¿Hay algún descuento hoy?','discount = DÍS-kaunt'],
  ['Do you have it in another color?','¿Lo tiene en otro color?','color = KÁ-ler'],
  ['It’s a little too big.','Me queda un poco grande.'],
  ['I’m just looking, thanks.','Solo estoy mirando, gracias.'],
  ['Can I return it if it doesn’t fit?','¿Lo puedo devolver si no me queda?'],
  ['Can I get a receipt, please?','¿Me da el recibo, por favor?','receipt = ri-SÍIT (la “p” no suena)'],
  ['Could you put it in a gift bag?','¿Me lo empaca en bolsa de regalo?']]},
 {k:'🏛️ Museos y tours',l:[
  ['We have a timed pass for ten o’clock.','Tenemos pase para las diez.'],
  ['Where does the tour start?','¿Dónde empieza el tour?','tour = TUR'],
  ['Can we take pictures here?','¿Podemos tomar fotos aquí?','pictures = PÍK-chers'],
  ['What’s the story behind this?','¿Cuál es la historia de esto?'],
  ['Could you take a picture of us, please?','¿Nos podría tomar una foto, por favor?'],
  ['Is there a free guided tour?','¿Hay un recorrido guiado gratis?','guided = GÁI-ded'],
  ['What time does the museum close?','¿A qué hora cierra el museo?','museum = miu-SÍ-om'],
  ['Where can we leave our backpacks?','¿Dónde podemos dejar las mochilas?'],
  ['Which exhibit do you recommend?','¿Qué exposición nos recomienda?','exhibit = ig-SÍ-bit']]},
 {k:'🌦️ Clima y planes',l:[
  ['Is it going to rain today?','¿Va a llover hoy?'],
  ['It’s freezing outside!','¡Está helando afuera!','freezing = FRÍI-sing'],
  ['What should we do if it rains?','¿Qué hacemos si llueve?'],
  ['What time is sunset?','¿A qué hora es el atardecer?','sunset = SÁN-set'],
  ['Do you think it will snow this week?','¿Cree que va a nevar esta semana?'],
  ['We’re going to New York tomorrow.','Mañana vamos a Nueva York.','tomorrow = tu-MÁ-rou']]},
 {k:'💊 Farmacia y salud',l:[
  ['I need something for a headache.','Necesito algo para el dolor de cabeza.','headache = JÉ-deik'],
  ['Do you have anything for a sore throat?','¿Tiene algo para el dolor de garganta?','throat = ZRÓUT'],
  ['I have a cold.','Tengo gripa.'],
  ['Is this medicine for adults?','¿Esta medicina es para adultos?','medicine = MÉ-di-sin'],
  ['I’m allergic to penicillin.','Soy alérgico a la penicilina.','allergic = a-LÉR-yik'],
  ['Where is the nearest pharmacy?','¿Dónde queda la farmacia más cercana?','pharmacy = FÁR-ma-si'],
  ['Please call an ambulance.','Por favor llamen una ambulancia.']]},
 {k:'📱 Teléfono e internet',l:[
  ['What’s the Wi-Fi password?','¿Cuál es la clave del wifi?','Wi-Fi = UÁI-fai · password = PÁS-uerd'],
  ['My phone is dead. Can I charge it here?','Se me descargó el celular. ¿Lo puedo cargar aquí?'],
  ['My eSIM isn’t working.','Mi eSIM no está funcionando.'],
  ['Can I use your charger for a minute?','¿Puedo usar su cargador un minuto?','charger = CHÁR-yer']]},
 {k:'🆘 Ayuda',l:[
  ['Excuse me, could you help me?','Disculpe, ¿me podría ayudar?','excuse = eks-KIÚS'],
  ['I’m lost. How do I get to the Capitol?','Estoy perdido. ¿Cómo llego al Capitolio?'],
  ['Could you speak more slowly, please?','¿Podría hablar más despacio, por favor?','slowly = SLÓU-li'],
  ['Sorry, could you repeat that?','Perdón, ¿lo puede repetir?'],
  ['How do you say this in English?','¿Cómo se dice esto en inglés?'],
  ['Where is the nearest restroom?','¿Dónde queda el baño más cercano?','restroom = RÉST-rum'],
  ['I lost my wallet.','Perdí mi billetera.','wallet = UÁ-let'],
  ['Can I borrow your phone?','¿Me presta su celular?']]},
 {k:'💬 Conversar',l:[
  ['We’re from Colombia.','Somos de Colombia.'],
  ['It’s our first time in the U.S.','Es nuestra primera vez en EE. UU.','first = FERST'],
  ['We’re visiting some friends here.','Estamos visitando a unos amigos aquí.'],
  ['What’s your favorite place in the city?','¿Cuál es tu lugar favorito de la ciudad?','favorite = FÉI-vo-rit'],
  ['What do you do for fun around here?','¿Qué se hace por aquí para divertirse?'],
  ['That sounds awesome!','¡Suena genial!','awesome = Á-som'],
  ['Nice to meet you!','¡Mucho gusto!'],
  ['Thank you so much for your help.','Muchas gracias por su ayuda.','thank: lengua entre los dientes'],
  ['Have a great day!','¡Que tengas un buen día!']]},
 {k:'🙏 Con los amigos que los reciben',l:[
  ['Thank you for having us.','Gracias por recibirnos.'],
  ['Can we help with dinner?','¿Les ayudamos con la comida?'],
  ['We’ll be back around nine.','Volvemos como a las nueve.'],
  ['What time do you usually have breakfast?','¿A qué hora desayunan normalmente?','breakfast = BRÉK-fast'],
  ['We bought you a little gift from Colombia.','Les trajimos un detalle de Colombia.']]}
];

/* Simulacro de migración: lo que pregunta el oficial y qué contestar */
var SIMULACRO=[
 ['What’s the purpose of your visit?','¿Cuál es el motivo de su viaje?','Tourism. I’m visiting some friends.','Turismo. Vengo a visitar a unos amigos.'],
 ['How long will you stay?','¿Cuánto tiempo se va a quedar?','Three weeks. I leave on November twenty-third.','Tres semanas. Me voy el 23 de noviembre.'],
 ['Where will you be staying?','¿Dónde se va a quedar?','With some friends in Arlington, Virginia.','Con unos amigos en Arlington, Virginia.'],
 ['Who are you traveling with?','¿Con quién viaja?','With my friend. We’re on vacation together.','Con mi amigo. Estamos de vacaciones juntos.'],
 ['Do you have a return ticket?','¿Tiene tiquete de regreso?','Yes, here it is.','Sí, aquí está.'],
 ['How much money are you bringing?','¿Cuánto dinero trae?','About … dollars, and my debit card.','Unos … dólares y mi tarjeta débito.'],
 ['What do you do in Colombia?','¿A qué se dedica en Colombia?','I’m a student. / I work as …','Soy estudiante. / Trabajo como …'],
 ['Do you have any food or anything to declare?','¿Trae comida o algo que declarar?','No, nothing to declare.','No, nada que declarar.'],
 ['Have you been to the United States before?','¿Ha estado antes en Estados Unidos?','No, this is my first time.','No, es mi primera vez.'],
 ['Welcome to the United States. Enjoy your stay.','Bienvenido a Estados Unidos. Disfrute su estadía.','Thank you very much!','¡Muchas gracias!']
];

/* Sonidos difíciles para hispanohablantes: escuchen la diferencia */
var SONIDOS=[
 {t:'i corta vs. i larga',p:[['ship','barco'],['sheep','oveja'],['live','vivir'],['leave','irse'],['sit','sentarse'],['seat','asiento']]},
 {t:'“th” (lengua entre los dientes)',p:[['three','tres'],['tree','árbol'],['think','pensar'],['sink','lavaplatos'],['thank you','gracias']]},
 {t:'“b” y “v” sí suenan distinto',p:[['very','muy'],['berry','mora'],['vest','chaleco'],['best','el mejor']]},
 {t:'“s” al inicio: no digan “es”',p:[['Spanish','español'],['street','calle'],['school','colegio'],['Starbucks','Starbucks']]},
 {t:'Terminaciones que sí suenan',p:[['walked','caminé'],['worked','trabajé'],['asked','pregunté'],['hats','sombreros']]},
 {t:'Números que se confunden',p:[['thirteen','13'],['thirty','30'],['fifteen','15'],['fifty','50']]}
];
