/* Restaurantes baratos y con buena experiencia, verificados el 5–6 oct 2026 (webs oficiales, Google y prensa local).
   c: ciudad · z: zona · p: precio por persona · pv: promedio en US$ · pide: qué pedir · por: por qué vale la pena
   ht: horario en texto · hs: [días (0=dom … 6=sáb, "1-5" = lun a vie), abre, cierra] (cierra > 24 = madrugada)
   conf: 'media' cuando el horario hay que confirmarlo cerca de la fecha. */
var RESTAURANTES = [
  /* ---------- Washington DC: National Mall y Capitolio ---------- */
  { n: 'Mitsitam Café', c: 'dc', z: 'National Mall', dir: 'Museo del Indígena Americano · 4th St & Independence Ave SW', ll: [38.8882, -77.0164], p: 'US$15–25', pv: 18, e: '🫓', pide: 'Fry bread y un plato de la estación', por: 'Comida indígena de todo el continente dentro de un museo gratis. Es el mejor almuerzo del Mall.', ht: 'Todos los días 11:00–16:00', hs: [['0-6', 11, 16]] },
  { n: 'Sweet Home Café', c: 'dc', z: 'National Mall', dir: 'Museo de Historia Afroamericana · 1400 Constitution Ave NW', ll: [38.8911, -77.0326], p: 'US$15–25', pv: 20, e: '🍗', pide: 'Pollo frito con mac & cheese', por: 'Comida del sur de EE. UU. con historia. Queda dentro del museo: sirve el día que tienen el pase.', ht: '11:00–15:00 · se necesita el pase del museo', hs: [['0-6', 11, 15]] },
  { n: 'Food trucks del Mall', c: 'dc', z: 'National Mall', dir: 'Maryland Ave SW y 7th St (y junto a los museos)', ll: [38.8850, -77.0220], p: 'US$10–15', pv: 12, e: '🚚', pide: 'Comparen: tacos, arepas, gyros, BBQ', por: 'Lo más barato entre museos. Coman en el césped del Mall.', ht: 'Sobre todo lun–vie 11:00–15:00', hs: [['1-5', 11, 15]], conf: 'media' },
  { n: 'Pavilion Café', c: 'dc', z: 'National Mall', dir: 'Jardín de esculturas de la National Gallery', ll: [38.8913, -77.0231], p: 'US$10–18', pv: 14, e: '☕', pide: 'Sándwich o sopa y chocolate caliente', por: 'Café con vidrio en medio de las esculturas. Desde finales de noviembre montan la pista de hielo.', ht: '10:00–16:00 (confirmar en noviembre)', hs: [['0-6', 10, 16]], conf: 'media' },
  { n: 'We, The Pizza', c: 'dc', z: 'Capitol Hill', dir: '305 Pennsylvania Ave SE', ll: [38.8869, -77.0017], p: 'US$8–14', pv: 11, e: '🍕', pide: 'Dos tajadas grandes y una soda artesanal', por: 'Pizza estilo Nueva York a 10 min del Capitolio.', ht: 'Todos los días 11:00–22:00', hs: [['0-6', 11, 22]] },
  { n: "Ted's Bulletin", c: 'dc', z: 'Capitol Hill', dir: '505 8th St SE', ll: [38.8823, -76.9951], p: 'US$15–22', pv: 18, e: '🥞', pide: 'Pop-tart casero y desayuno todo el día', por: 'Diner retro con los pop-tarts hechos en casa. Muy de foto.', ht: 'Dom–jue 7:00–22:00 · vie–sáb hasta 23:00', hs: [['0-4', 7, 22], ['5-6', 7, 23]] },
  { n: 'Market Lunch (Eastern Market)', c: 'dc', z: 'Capitol Hill', dir: '225 7th St SE', ll: [38.8865, -76.9965], p: 'US$10–22', pv: 14, e: '🦀', pide: 'Blue bucks pancakes (fin de semana) o crab cake', por: 'Mostrador clásico dentro del mercado más viejo de DC. Hay fila pero vale la pena.', ht: 'Mar–jue 8:00–14:15 · vie–sáb hasta 14:30 · dom 9:00–14:30 · lun cerrado', hs: [['2-4', 8, 14.25], ['5-6', 8, 14.5], ['0', 9, 14.5]] },
  /* ---------- Georgetown y Foggy Bottom ---------- */
  { n: 'Western Market', c: 'dc', z: 'Foggy Bottom', dir: '2000 Pennsylvania Ave NW', ll: [38.9005, -77.0450], p: 'US$8–18', pv: 13, e: '🍜', pide: 'Lo que quieran: hay ramen, tacos, bowls y postres', por: 'Food hall nuevo: cada uno escoge lo suyo. Queda camino a Georgetown y al Kennedy Center.', ht: 'Lun–vie 7:00–22:00 · sáb–dom 8:00–22:00', hs: [['1-5', 7, 22], ['0', 8, 22], ['6', 8, 22]] },
  { n: 'Call Your Mother Deli', c: 'dc', z: 'Georgetown', dir: '3428 O St NW', ll: [38.9076, -77.0690], p: 'US$10–16', pv: 12, e: '🥯', pide: 'Bagel "Amar\'e" o el de huevo y queso', por: 'Los bagels más famosos de DC en una casita rosada. Lleguen temprano.', ht: 'Todos los días 7:30–14:00', hs: [['0-6', 7.5, 14]] },
  { n: 'Falafel Inc (Georgetown)', c: 'dc', z: 'Georgetown', dir: '1210 Potomac St NW', ll: [38.9051, -77.0655], p: 'US$5–9', pv: 7, e: '🧆', pide: 'Bowl o sándwich de falafel', por: 'Lo más barato y rico de Georgetown. Parte de lo que pagan ayuda a refugiados.', ht: 'Todos los días desde las 12:00', hs: [['0-6', 12, 21]], conf: 'media' },
  { n: 'Baked & Wired', c: 'dc', z: 'Georgetown', dir: '1052 Thomas Jefferson St NW', ll: [38.9037, -77.0601], p: 'US$8–14', pv: 9, e: '🧁', pide: 'Cupcake y café', por: 'La pastelería que los de Georgetown prefieren. Junto al canal C&O.', ht: 'Todos los días 8:00–16:00', hs: [['0-6', 8, 16]] },
  { n: 'Chaia Tacos', c: 'dc', z: 'Georgetown', dir: '3207 Grace St NW', ll: [38.9040, -77.0618], p: 'US$12–18', pv: 15, e: '🌮', pide: 'Tacos vegetarianos de temporada', por: 'Tacos de verduras de granja que sorprenden. Pequeño y bonito.', ht: 'Almuerzo y cena (confirmar)', conf: 'media' },
  /* ---------- U Street, Adams Morgan y Dupont ---------- */
  { n: "Ben's Chili Bowl", c: 'dc', z: 'U Street', dir: '1213 U St NW', ll: [38.9170, -77.0287], p: 'US$12–18', pv: 15, e: '🌭', pide: 'Half-smoke "all the way" y papas con chili', por: 'Un ícono de DC desde 1958 (reabrió el 1 may 2026). Pidan como los locales.', ht: 'Dom–jue 11:00–23:00 · vie–sáb hasta las 4:00', hs: [['0-4', 11, 23], ['5-6', 11, 28]] },
  { n: 'Pizza Mart (jumbo slice)', c: 'dc', z: 'Adams Morgan', dir: '2445 18th St NW', ll: [38.9216, -77.0425], p: 'US$7–10', pv: 8, e: '🍕', pide: 'Una jumbo slice para compartir', por: 'La tajada gigante original de Adams Morgan. Es plan de noche.', ht: 'Solo de noche: lun–jue 18:00–3:00 (fin de semana más tarde)', hs: [['1-4', 18, 27], ['5-6', 18, 28], ['0', 18, 27]], conf: 'media' },
  { n: 'Dukem', c: 'dc', z: 'U Street', dir: '1114 U St NW', ll: [38.9168, -77.0277], p: 'US$16–25', pv: 20, e: '🫓', pide: 'Combo de carne y verduras con injera, para compartir', por: 'DC tiene la comunidad etíope más grande de EE. UU.: se come con la mano.', ht: 'Desde las 17:00 (fin de semana desde las 15:00)', hs: [['1-5', 17, 23], ['0', 15, 23], ['6', 15, 23]], conf: 'media' },
  { n: "Oohh's & Aahh's", c: 'dc', z: 'U Street', dir: '1005 U St NW', ll: [38.9169, -77.0263], p: 'US$15–22', pv: 18, e: '🍗', pide: 'Pollo frito o salmón con dos acompañantes', por: 'Comida casera del sur, porciones enormes. Para compartir.', ht: 'Almuerzo y cena', conf: 'media' },
  { n: 'Kramers', c: 'dc', z: 'Dupont Circle', dir: '1517 Connecticut Ave NW', ll: [38.9104, -77.0438], p: 'US$18–28', pv: 22, e: '📚', pide: 'Brunch o un postre', por: 'Librería con restaurante adentro. Perfecto si llueve.', ht: 'Todos los días (confirmar horas)', conf: 'media' },
  { n: 'Mercado FRESHFARM de Dupont', c: 'dc', z: 'Dupont Circle', dir: '1500 20th St NW', ll: [38.9098, -77.0454], p: 'US$5–15', pv: 10, e: '🧺', pide: 'Sidra caliente y algo de panadería', por: 'Mercado de granjeros del domingo: muy local.', ht: 'Solo domingos 8:30–13:30', hs: [['0', 8.5, 13.5]] },
  /* ---------- Union Market ---------- */
  { n: 'Union Market', c: 'dc', z: 'NoMa', dir: '1309 5th St NE', ll: [38.9087, -76.9975], p: 'US$12–20', pv: 16, e: '🛒', pide: 'Recorran antes de escoger: arepas, dumplings, tacos, helado', por: 'El food hall más famoso de DC, en el plan del último día.', ht: 'Lun–sáb 8:00–21:00 · dom hasta 20:00', hs: [['1-6', 8, 21], ['0', 8, 20]] },
  { n: 'La Cosecha', c: 'dc', z: 'NoMa', dir: '1280 4th St NE', ll: [38.9075, -76.9993], p: 'US$10–18', pv: 14, e: '🫔', pide: 'Pupusas o un sándwich de Peruvian Brothers', por: 'Mercado latino al lado de Union Market. Sabor a casa.', ht: 'Almuerzo y cena (algunos puestos cierran lunes)', conf: 'media' },
  /* ---------- The Wharf y Navy Yard ---------- */
  { n: 'Municipal Fish Market', c: 'dc', z: 'The Wharf', dir: '1100 Maine Ave SW', ll: [38.8807, -77.0247], p: 'US$12–25', pv: 18, e: '🦀', pide: 'Cangrejos al vapor con Old Bay o un sándwich de pescado', por: 'El mercado de pescado al aire libre más antiguo de EE. UU. Coman mirando el río.', ht: 'Lun–jue 10:00–20:00 (fin de semana más tarde)', hs: [['1-4', 10, 20], ['5-6', 10, 21], ['0', 10, 20]], conf: 'media' },
  { n: 'Falafel Inc (The Wharf)', c: 'dc', z: 'The Wharf', dir: '1140 Maine Ave SW', ll: [38.8795, -77.0243], p: 'US$6–10', pv: 8, e: '🧆', pide: 'Bowl de falafel', por: 'Barato, rápido y frente al agua: perfecto antes del atardecer.', ht: 'Todos los días (confirmar)', conf: 'media' },
  { n: 'Taco City DC', c: 'dc', z: 'Navy Yard', dir: '1102 8th St SE', ll: [38.8770, -76.9951], p: 'US$10–15', pv: 12, e: '🌮', pide: 'Tacos al pastor', por: 'Tacos de verdad a buen precio.', ht: 'Martes a domingo (lunes cerrado)', hs: [['2-6', 11, 22], ['0', 11, 22]], conf: 'media' },
  /* ---------- Arlington ---------- */
  { n: 'El Pollo Rico', c: 'arl', z: 'Ballston', dir: '932 N Kenmore St', ll: [38.8808, -77.1105], p: 'US$10–15', pv: 12, e: '🍗', pide: 'Medio pollo con yuca frita y las dos salsas', por: 'Pollo a la brasa peruano legendario de Arlington. Ojo: el de N Washington Blvd cerró; vayan a este.', ht: 'Todos los días 11:00–22:00', hs: [['0-6', 11, 22]] },
  { n: "Hot Lola's", c: 'arl', z: 'Ballston', dir: 'Ballston Quarter · 4238 Wilson Blvd', ll: [38.8812, -77.1116], p: 'US$12–16', pv: 14, e: '🌶️', pide: 'Sándwich de pollo picante (pidan nivel medio)', por: 'Pollo picante estilo Nashville dentro de un food hall cubierto.', ht: '11:30–20:00', hs: [['0-6', 11.5, 20]], conf: 'media' },
  { n: 'The Italian Store', c: 'arl', z: 'Lyon Village', dir: '3123 Langston Blvd', ll: [38.8964, -77.0988], p: 'US$10–16', pv: 12, e: '🥪', pide: 'Sándwich "Milano" o una pizza para llevar', por: 'Deli italiano de barrio con sándwiches enormes: almuerzo para dos días.', ht: 'Todos los días (confirmar)', conf: 'media' },
  { n: 'Lebanese Taverna (Pentagon Row)', c: 'arl', z: 'Pentagon City', dir: '1101 S Joyce St', ll: [38.8625, -77.0632], p: 'US$16–25', pv: 20, e: '🥙', pide: 'Mezze para compartir y shawarma', por: 'Cena rica después de las compras en Pentagon City.', ht: 'Almuerzo y cena', conf: 'media' },
  { n: "Bob & Edith's Diner", c: 'arl', z: 'Columbia Pike', dir: '2310 Columbia Pike', ll: [38.8622, -77.0857], p: 'US$10–16', pv: 13, e: '🍳', pide: 'Desayuno americano a cualquier hora', por: 'Diner abierto 24 horas: experiencia americana clásica. (El de Langston Blvd cerró.)', ht: 'Abierto 24 horas', hs: [['0-6', 0, 24]] },
  /* ---------- Old Town Alexandria ---------- */
  { n: 'Royal Restaurant', c: 'arl', z: 'Old Town', dir: '730 N St Asaph St', ll: [38.8130, -77.0453], p: 'US$14–22', pv: 17, e: '🍳', pide: 'Desayuno o hamburguesa', por: 'Funciona desde 1904: el diner más viejo de Alexandria.', ht: 'Desayuno y almuerzo (confirmar)', conf: 'media' },
  { n: 'The Pita House', c: 'arl', z: 'Old Town', dir: '719 King St', ll: [38.8050, -77.0475], p: 'US$12–18', pv: 14, e: '🥙', pide: 'Shawarma o plato de falafel', por: 'Barato en la calle más bonita de Old Town.', ht: 'Almuerzo y cena', conf: 'media' },
  { n: 'Fish Market', c: 'arl', z: 'Old Town', dir: '105 King St', ll: [38.8046, -77.0410], p: 'US$18–28', pv: 22, e: '🐟', pide: 'Fish & chips o sopa de almejas', por: 'Edificio histórico frente al muelle. Un gusto si el presupuesto da.', ht: 'Almuerzo y cena', conf: 'media' },
  { n: "Pop's Old Fashioned Ice Cream", c: 'arl', z: 'Old Town', dir: '109 King St', ll: [38.8046, -77.0412], p: 'US$6–10', pv: 7, e: '🍦', pide: 'Un cono con dos sabores', por: 'Heladería antigua junto al muelle. El postre del sábado.', ht: 'Tarde y noche', conf: 'media' },
  /* ---------- Nueva York ---------- */
  { n: 'Liberty Bagels Midtown', c: 'ny', z: 'Midtown', dir: '260 W 35th St', ll: [40.7524, -73.9926], p: 'US$5–10', pv: 7, e: '🥯', pide: 'Rainbow bagel con queso crema de fresa', por: 'A 3 cuadras de Penn Station: el desayuno de llegada, colorido y barato.', ht: 'Lun–vie 6:00–17:00', hs: [['1-5', 6, 17]] },
  { n: "Joe's Pizza (Broadway)", c: 'ny', z: 'Times Square', dir: '1435 Broadway', ll: [40.7547, -73.9870], p: 'US$4–10', pv: 6, e: '🍕', pide: 'Plain slice: se dobla y se come de pie', por: 'La tajada clásica de Nueva York a pasos de Times Square.', ht: 'Todos los días 10:00–3:00', hs: [['0-6', 10, 27]] },
  { n: 'The Halal Guys', c: 'ny', z: 'Midtown', dir: 'Esquina suroeste de 53rd St y 6th Ave', ll: [40.7616, -73.9792], p: 'US$10–13', pv: 11, e: '🥘', pide: 'Chicken over rice, salsa blanca (la roja pica mucho)', por: 'El carrito más famoso del mundo, camino a Central Park.', ht: 'Desde las 10:00 hasta la madrugada', hs: [['0-6', 10, 28]], conf: 'media' },
  { n: 'Los Tacos No. 1 (Tribeca)', c: 'ny', z: 'Downtown', dir: '136 Church St', ll: [40.7148, -74.0093], p: 'US$6–15', pv: 12, e: '🌮', pide: 'Adobada y carne asada en tortilla de harina', por: 'Los tacos más famosos de NY, a 5 min del Memorial del 11-S.', ht: 'Lun–sáb 11:00–23:00', hs: [['1-6', 11, 23]] },
  { n: 'Time Out Market', c: 'ny', z: 'DUMBO', dir: '55 Water St, Brooklyn', ll: [40.7034, -73.9906], p: 'US$8–20', pv: 15, e: '🌉', pide: 'Lo que quieran, y suban a la terraza', por: 'Terraza gratis con vista al puente de Brooklyn y Manhattan: cena con la mejor vista.', ht: 'Todos los días hasta la noche', conf: 'media' },
  { n: "Juliana's", c: 'ny', z: 'DUMBO', dir: '19 Old Fulton St, Brooklyn', ll: [40.7027, -73.9934], p: 'US$12–20', pv: 16, e: '🍕', pide: 'Una pizza margherita entera para compartir', por: 'Pizza de horno de carbón debajo del puente de Brooklyn.', ht: '11:30–15:15 y 16:00–21:00', hs: [['0-6', 11.5, 21]] },
  /* ---------- Baltimore ---------- */
  { n: "Faidley's (Lexington Market)", c: 'bal', z: 'Lexington Market', dir: 'Puesto 21 · Lexington Market', ll: [39.2917, -76.6205], p: 'US$16–26', pv: 22, e: '🦀', pide: 'Crab cake "jumbo lump" (compartan uno)', por: 'El crab cake más famoso de Baltimore, desde 1886.', ht: 'Jue–sáb 10:00–17:30 · dom cerrado', hs: [['4-6', 10, 17.5]], conf: 'media' },
  { n: 'Market Bakery (Berger cookies)', c: 'bal', z: 'Lexington Market', dir: 'Lexington Market', ll: [39.2916, -76.6203], p: 'US$3–8', pv: 5, e: '🍪', pide: 'Berger cookie (galleta con capa gruesa de chocolate)', por: 'El dulce típico de Baltimore: buen regalo.', ht: 'Horario del mercado', conf: 'media' },
  { n: 'The Golden Pretzel', c: 'bal', z: 'Fells Point', dir: 'Broadway Market · 1640 Aliceanna St', ll: [39.2837, -76.5933], p: 'US$5–12', pv: 8, e: '🥨', pide: 'Pretzel relleno', por: 'Snack barato en el puerto más bonito de Baltimore.', ht: 'Horario del mercado', conf: 'media' },
  { n: 'Taco Love Grill (Cross Street Market)', c: 'bal', z: 'Federal Hill', dir: '1065 S Charles St', ll: [39.2766, -76.6136], p: 'US$10–15', pv: 12, e: '🌮', pide: 'Tacos y elote', por: 'Al pie de Federal Hill, antes del atardecer.', ht: 'Vie–sáb 11:00–21:00', hs: [['5-6', 11, 21]], conf: 'media' },
  /* ---------- Filadelfia ---------- */
  { n: "Uncle Gus' Steaks (Reading Terminal)", c: 'phi', z: 'Reading Terminal Market', dir: 'Puesto A8 · Reading Terminal Market', ll: [39.9533, -75.1590], p: 'US$18–20', pv: 19, e: '🥩', pide: 'Cheesesteak "wit" (con cebolla)', por: 'Cheesesteak dentro del mercado techado: sin frío ni filas de turistas en la calle.', ht: 'Todos los días 10:00–18:00', hs: [['0-6', 10, 18]] },
  { n: "DiNic's (Reading Terminal)", c: 'phi', z: 'Reading Terminal Market', dir: 'Puesto B5 · Reading Terminal Market', ll: [39.9533, -75.1592], p: 'US$14–18', pv: 16, e: '🥪', pide: 'Roast pork con broccoli rabe y provolone', por: 'Muchos dicen que es mejor que el cheesesteak. Compartan uno de cada uno.', ht: 'Lun–sáb 9:00–17:00', hs: [['1-6', 9, 17]] },
  { n: "Beiler's Doughnuts", c: 'phi', z: 'Reading Terminal Market', dir: 'Reading Terminal Market', ll: [39.9535, -75.1595], p: 'US$2–8', pv: 5, e: '🍩', pide: 'Dos donas recién hechas', por: 'Donas de una familia amish, hechas a la vista.', ht: 'Lun–sáb 8:00–18:00', hs: [['1-6', 8, 18]] },
  { n: "Hershel's East Side Deli", c: 'phi', z: 'Reading Terminal Market', dir: 'Reading Terminal Market', ll: [39.9532, -75.1588], p: 'US$14–20', pv: 17, e: '🥪', pide: 'Sándwich de pastrami', por: 'Deli judío clásico, para el que no quiera cheesesteak.', ht: 'Horario del mercado', conf: 'media' },
  { n: "Campo's", c: 'phi', z: 'Old City', dir: '214 Market St', ll: [39.9500, -75.1442], p: 'US$14–18', pv: 16, e: '🥩', pide: 'Cheesesteak clásico', por: 'Cheesesteak de familia a 5 min de la Liberty Bell.', ht: 'Lun–sáb 9:30–22:00', hs: [['1-6', 9.5, 22]], conf: 'media' },
  /* ---------- Delaware ---------- */
  { n: 'Shake Shack (Christiana)', c: 'del', z: 'Christiana Mall', dir: '2120 Fashion Center Blvd', ll: [39.6745, -75.6440], p: 'US$12–18', pv: 15, e: '🍔', pide: 'ShackBurger y malteada', por: 'Hamburguesa rica para cerrar el día de compras.', ht: 'Almuerzo y cena', conf: 'media' },
  { n: 'Food court de Christiana Mall', c: 'del', z: 'Christiana Mall', dir: 'Dentro del centro comercial', ll: [39.6776, -75.6527], p: 'US$10–15', pv: 12, e: '🛍️', pide: 'Charleys (cheesesteak) u otro', por: 'Rápido entre tienda y tienda.', ht: 'Horario del centro comercial', conf: 'media' },
  { n: 'Wawa', c: 'del', z: 'Christiana', dir: '970 Christiana Rd', ll: [39.6610, -75.6500], p: 'US$6–10', pv: 8, e: '🥤', pide: 'Hoagie hecho al momento', por: 'La tienda 24 h que los de la zona aman: barata para el tren de regreso.', ht: 'Abierto 24 horas', hs: [['0-6', 0, 24]] }
];

/* Supermercados para comer en casa y armar sándwiches (lo más barato) */
var MERCADOS = [
  { n: "Trader Joe's Clarendon", dir: '1109 N Highland St', ll: [38.8858, -77.0956], nota: 'El único de Arlington. Barato y con snacks únicos (buen regalo). 8:00–21:00.' },
  { n: 'Harris Teeter Pentagon Row', dir: '900 Army Navy Dr', ll: [38.8640, -77.0625], nota: 'Supermercado completo junto a Pentagon City.' },
  { n: 'Whole Foods Pentagon City', dir: '520 12th St S', ll: [38.8628, -77.0532], nota: 'Más caro, pero con comida caliente por libra.' }
];

/* Cerrados: no los recomienden aunque salgan en guías viejas */
var CERRADOS = ["Ray's Hell Burger (todas las sedes)", 'Good Stuff Eatery Capitol Hill (cerró en feb 2026)', 'Amsterdam Falafelshop', "El Pollo Rico de N Washington Blvd", "Bob & Edith's de Langston Blvd"];
